<?php

namespace di\RankingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * classementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classementRepository extends EntityRepository
{
	/**
	 * Get current ranking
	 *
	 * @return array()
	 */
	public function getCurrentRanking()
	{
		$em = $this->getEntityManager();
	
		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->addSelect('eq');
		$qb->addSelect('ep');
		$qb->from('diRankingBundle:classement','c');
		$qb->leftJoin('c.idEquipe', 'eq');
		$qb->leftJoin('c.idEpreuve', 'ep');
	
		$response = $qb->getQuery()->getResult();
		
		$ranking = array();
		
		foreach ($response as $results)
		{
			$nomEquipe = $results->getIdEquipe()->getNom();
			$pointsEquipe = $results->getPoints();
			
			if (isset($ranking[$nomEquipe]))
			{
				$ranking[$nomEquipe] += $pointsEquipe;
			}
			else 
			{
				$ranking[$nomEquipe] = $pointsEquipe;
			}
			
		}
		
		array_multisort($ranking, SORT_DESC);
		
		return $ranking;
	}
	
	/**
	 * Get by epreuve ordered
	 *
	 * @return array()
	 */
	public function findByEpreuveOrdered($id)
	{
		$em = $this->getEntityManager();
	
		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->addSelect('eq');
		$qb->addSelect('ep');
		$qb->from('diRankingBundle:classement','c');
		$qb->leftJoin('c.idEquipe', 'eq');
		$qb->leftJoin('c.idEpreuve', 'ep');
		$qb->where('ep.id = :id');
		$qb->orderBy('c.position', 'ASC');
		
		$qb->setParameter('id', $id);
		
		
		return $qb->getQuery()->getResult();
	
	}
	
	
	
}
