<?php

namespace di\RankingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * equipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipeRepository extends EntityRepository
{
}
